### ISSUE TITLE
MapEditor: Increase precision of Scale values to hundredths

### ISSUE THREAD

**Issue by MiningPie** [oberien/refunct-tas#236] opened 2023-06-05 23:14 UTC
Despite only displaying 1 decimal point, the editor is able to handle many more. I'm often using values such as 1.25 or 1.375 to accurately adjust the scale of a platform to precise values, but it gets confusing when it only displays the value "1.4"

Displaying 2 decimal points of precision should be enough to resolve the vast majority of cases that currently cause confusion.

**Comment by LukeSaward1** [comment] 2023-06-06 01:24
What could be a good solution is it figures out the amount of decimal places needed and sets the decimal places to that.

e.g.
you enter 1.345, it displays 1.345
you enter 1.4, it displays 1.4

**Comment by oberien** [comment] 2023-06-06 07:40
The problem is float uncertainties. For example `0.1 + 0.2` is `0.30000000000000004`. Also some values Refunct uses are super weird like `89.997` for rotation. We can't know if such input should be exact or is a float precision error.

**Comment by oberien** [comment] 2023-06-06 11:07
Closing as superseded by #237

**Closed by oberien** 2023-06-06 11:07 UTC
Labels: rebo
