### ISSUE TITLE
v0.9.6 Release still has "New version available" text

### ISSUE THREAD

**Issue by MiningPie** [oberien/refunct-tas#264] opened 2023-06-11 01:54 UTC
![image](https://github.com/oberien/refunct-tas/assets/95598570/c239aa38-b548-4ed6-8115-927ebb895d9a)
I just downloaded v0.9.6 however it says im still on 0.9.5 and should update, I've checked the source code and think the version likely just wasn't updated.

**Comment by LukeSaward1** [comment] 2023-06-11 07:24
This is correct.
_Somebody_ (iirc oberien) forgot to change it in 0.9.6 release.

It will be fixed for 0.9.7

**Comment by oberien** [comment] 2023-06-11 08:50
Duplicate of #261.

**Closed by oberien** 2023-06-11 08:50 UTC
