### ISSUE TITLE
Practice Mode breaks the standard map

### ISSUE THREAD

**Issue by oberien** [oberien/refunct-tas#281] opened 2023-06-24 14:23 UTC
Another variant of #273, where you don't even need the map editor.

Reproduction steps:

- Load refunct-tas (I used [this build](https://ci.appveyor.com/api/buildjobs/jwl3t9djglbl3vwq/artifacts/build%2Fpractice-windows.zip))
- Practice Button 30 or 31
- Hit New Game
- Look at cluster 24 and 25's springpads

_Originally posted by @LukeSaward1 in https://github.com/oberien/refunct-tas/issues/273#issuecomment-1605058208_

It only happens to: 24s1, 25s1, 26s1, 25pi1

**Comment by MiningPie** [comment] 2023-07-21 04:38
Every element affected by this issue seems to be mislabled.
![image](https://github.com/oberien/refunct-tas/assets/95598570/35cc3fa5-fd01-42e3-9425-e0a2e87abb90)
This pipe rises with cluster 24 but is assigned to cluster 25

![image](https://github.com/oberien/refunct-tas/assets/95598570/f2f1e3ed-2f89-4834-9bba-b2948ab6477f)
This springpad rises with cluster 24 but is assigned as 25s1

![image](https://github.com/oberien/refunct-tas/assets/95598570/879162b7-7865-427c-9351-8b09afb3ec22)
This springpad rises with cluster 25 but is assigned as 26s1

![image](https://github.com/oberien/refunct-tas/assets/95598570/4cb08841-a3f2-4989-86ad-a13ffeef90f7)
This springpad also rises with cluster 25 but is assigned as 24s1

This mislabeling of 24pi1 was posted in #284, but seeing as every object affect by the above issue is mislabeled it is very likely the issue is linked.

**Closed** 2023-11-27 09:18 UTC
Labels: bug, rebo, rtil
