### ISSUE TITLE
Map Editor: Platform values do not update when setting to player location/resetting to original values

### ISSUE THREAD

**Issue by MiningPie** [oberien/refunct-tas#266] opened 2023-06-11 02:12 UTC
https://github.com/oberien/refunct-tas/assets/95598570/01278d41-a990-42d2-9cc1-e025f3d0a0e4

**Comment by oberien** [comment] 2023-06-11 08:49
Duplicate of #260.

**Closed by oberien** 2023-06-11 08:49 UTC
